sudo: required
services:
  - docker
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_install:
  - docker pull wala/platformio-node-proto
script:
  - ./example.sh
